services:
  adguard:
    image: adguard/adguardhome
    networks:
        - diagon-alley
    ports:
      - 53:53/tcp
      - 53:53/udp
    volumes:
      - adguard-data:/opt/adguardhome/work
      - adguard-config:/opt/adguardhome/conf
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == ??
      restart_policy:
        condition: on-failure
      labels:
          - "traefik.enable=true"
          - "traefik.swarm.network=diagon-alley"

          # Authelia web interface
          - "traefik.http.routers.adguard.rule=Host(`adguard.hogwartsnetwork.co.uk`)"
          - "traefik.http.routers.adguard.entrypoints=websecure"
          - "traefik.http.routers.adguard.tls=true"
          - "traefik.http.routers.adguard.tls.certresolver=cloudflare"
    
          # Authelia listens on 9091
          - "traefik.http.services.adguard.loadbalancer.server.port=3020"

volumes:
  adguard-data:
    external: false
    name: adguard-data

  adguard-config:
    external: false
    name: adguard-config
  
networks:
  diagon-alley:
    external: true