services:
  technitium:
    image: technitium/dns-server:latest

    hostname: technitium

    environment:
      DNS_SERVER_DOMAIN: dns.hogwartsnetwork.co.uk
      DNS_SERVER_LOG_USING_LOCAL_TIME: "true"

    volumes:
      - technitium_config:/etc/dns

    ports:
      - target: 53
        published: 53
        protocol: tcp
        mode: host

      - target: 53
        published: 53
        protocol: udp
        mode: host

    networks:
      - diagon-alley

    deploy:
      replicas: 1

      placement:
        constraints:
          - node.hostname == rpi-2

      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=diagon-alley"

        # HTTP router
        - "traefik.http.routers.technitium.rule=Host(`dns.hogwartsnetwork.co.uk`)"
        - "traefik.http.routers.technitium.entrypoints=websecure"
        - "traefik.http.routers.technitium.tls=true"

        # Technitium web interface
        - "traefik.http.services.technitium.loadbalancer.server.port=5380"

networks:
  diagon-alley:
    external: true

volumes:
  technitium_config: