services:
  termix:
    image: ghcr.io/lukegus/termix:beta-2.7.1-beta.
    restart: unless-stopped
    environment:
      - TZ=Europe/London
    volumes:
      # - termix_data:/app/data
      
      - type: volume
        source: docker-volumes
        target: /app/data
        volume:
          subpath: termix # The subdirectory inside the volume
    networks:
      - diagon-alley
    labels:
        - "diun.enable=true"
        
        - "traefik.enable=true"

        # Router
        - "traefik.http.routers.termix.rule=Host(`terminal.hogwartsnetwork.co.uk`)"
        - "traefik.http.routers.termix.entrypoints=websecure"
        - "traefik.http.routers.termix.tls=true"
        - "traefik.http.routers.termix.tls.certresolver=cloudflare"

        # Service
        - "traefik.http.services.termix.loadbalancer.server.port=8080"

        # Network
        - "traefik.docker.network=diagon-alley"

networks:
  diagon-alley:
    external: true

volumes:
  # termix_data:

  docker-volumes:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.100.5,rw,nfsvers=4
      device: ":/mnt/Hogwarts-Vault/DockerVolumes"