services:
  termix:
    image: ghcr.io/lukegus/termix:beta-2.7.1-beta.20260822
    environment:
      - TZ=Europe/London
    volumes:
      - termix_data:/app/data
    networks:
      - diagon-alley
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"

        # Router
        - "traefik.http.routers.termix.rule=Host(`termix.hogwartsnetwork.co.uk`)"
        - "traefik.http.routers.termix.entrypoints=websecure"
        - "traefik.http.routers.termix.tls=true"
        - "traefik.http.routers.termix.tls.certresolver=cloudflare"

        # Service
        - "traefik.http.services.termix.loadbalancer.server.port=3000"

networks:
  diagon-alley:
    external: true

volumes:
  termix_data: