services:
  prometheus:
    image: prom/prometheus
    #ports:
    #  - 9090:9090
    networks:
      - monitoring-internal
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == srv-01
      restart_policy:
        condition: on-failure

networks:
  diagon-alley:
    external: true

  monitoring-internal:
    external: true
    name: monitoring-internal