services:
  jellyfin:
    image: ghcr.io/jellyfin/jellyfin:10.11.11
    volumes:
      # Uses the docker volumes configured in the volumes section below to persist Jellyfin configuration and cache data
      - jellyfin-config:/config
      - jellyfin-cache:/cache

      # Uses the shared bind mounts configured in the volumes section below to access media on the host
      - movies:/movies
      - shows:/shows
      - books:/books
      - music:/music
    networks:
      - media
      - diagon-alley
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.media == yes
      restart_policy:
        condition: on-failure
      labels:
        # Enable Traefik
        - "traefik.enable=true"
        # Tell Traefik which network to use
        - "traefik.swarm.network=diagon-alley"
        # HTTP router
        - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.hogwartsnetwork.co.uk`)"
        - "traefik.http.routers.jellyfin.entrypoints=websecure"
        # HTTPS
        - "traefik.http.routers.jellyfin.tls=true"
        # Paperless internal port
        - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"

  seerr:
    image: ghcr.io/seerr-team/seerr:v3.4.1
    init: true
    container_name: seerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/London
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      # Uses the docker volumes configured in the volumes section below to persist Seerr configuration data
      - seerr-config:/app/config
    networks:
      - media
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/settings/public || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.media == yes
      restart_policy:
        condition: on-failure

  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:release-6.3.0.10514
    ports:
      - "7878:7878"
    environment:
      - PUID=0
      - PGID=0
      - UMASK=002
      - TZ=Europe/London
      - WEBUI_PORTS=7878/tcp 
    volumes:
      - radarr-config:/config
      - movies:/movies
    networks:
      - media
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.media == yes
      restart_policy:
        condition: on-failure

  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:release-4.0.19.2979
    ports:
      - "8989:8989"
    environment:
      - PUID=0
      - PGID=0
      - UMASK=002
      - TZ=Europe/London
      - WEBUI_PORTS=8989/tcp 
    volumes:
      - sonarr-config:/config
      - shows:/shows
    networks:
      - media
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.media == yes
      restart_policy:
        condition: on-failure
    
volumes:
  jellyfin-config:
    external: false
    name: jellyfin-config

  seerr-config:
    external: false
    name: seerr-config

  radarr-config:
    external: false
    name: radarr-config

  sonarr-config:
    external: false
    name: sonarr-config

  jellyfin-cache:
    external: false
    name: jellyfin-cache

  movies:
    driver: local
    driver_opts:
      type: none
      device: /mnt/movies
      o: bind

  shows:
    driver: local
    driver_opts:
      type: none
      device: /mnt/shows
      o: bind

  books:
    driver: local
    driver_opts:
      type: none
      device: /mnt/books
      o: bind

  music:
    driver: local
    driver_opts:
      type: none
      device: /mnt/music
      o: bind

networks:
  media:
    driver: overlay
    # attachable: true
    external: false

  diagon-alley:
    external: true
