services:
  makemkv:
    image: jlesage/makemkv
    restart: unless-stopped
    ports:
      - "5800:5800"
    environment:
      WEB_FILE_MANAGER: "1"
    volumes:
      - makemkv-config:/config:rw"
      - raw-ingest:/output:rw"
    devices:
      - "/dev/sr0:/dev/sr0"
      - "/dev/sg0:/dev/sg0"

  mkvtoolnix:
    image: jlesage/mkvtoolnix
    ports:
      - "5801:5800"
    volumes:
      - mkvtoolnix-config:/config:rw
      - raw-ingest:/raw-ingest:rw
      - filtered-ingest:/filtered-ingest:rw

volumes:
  makemkv-config:
    external: false
    name: makemkv-config

  mkvtoolnix-config:
    external: false
    name: mkvtoolnix-config

  raw-ingest:
    external: false
    name: raw-ingest

  filtered-ingest:
    external: false
    name: filtered-ingest