services:
  makemkv:
    image: jlesage/makemkv
    restart: unless-stopped
    ports:
      - "5800:5800"
    environment:
      - WEB_FILE_MANAGER=1
    volumes:
      - makemkv-config:/config:rw
      - raw-ingest:/output:rw
    devices:
      - "/dev/sr0:/dev/sr0"
      - "/dev/sg0:/dev/sg0"

  filebot:
    image: jlesage/filebot
    ports:
      - "5801:5800"
    environment:
      - WEB_FILE_MANAGER=1
    volumes:
      - filebot-config:/config:rw
      - raw-ingest:/storage:rw

  #mkvtoolnix:
  #  image: jlesage/mkvtoolnix
  #  ports:
  #    - "5802:5800"
  #  volumes:
  #    - mkvtoolnix-config:/config:rw
  #    - raw-ingest:/storage/raw-ingest:rw
  #    - movies-ingest:/storage/movies-ingest:rw
  #    - shows-ingest:/storage/shows-ingest:rw

  mkvcleaver:
    image: jlesage/mkvcleaver
    ports:
      - "5802:5800"
    volumes:
      - mkvcleaver-config:/config:rw
      - raw-ingest:/storage:rw
      - movies-ingest:/storage/movies-ingest:rw
      - shows-ingest:/storage/shows-ingest:rw

  handbrake:
    image: jlesage/handbrake
    ports:
      - "5803:5800"
    volumes:
      - handbrake-config:/config:rw
      - movies-ingest:/watch/movies:rw
      - shows-ingest:/watch/shows:rw
      - movies:/movies:rw
      - shows:/shows:rw

volumes:
  makemkv-config:
    external: false
    name: makemkv-config

  filebot-config:
    external: false
    name: filebot-config

  mkvtoolnix-config:
    external: false
    name: mkvtoolnix-config

  mkvcleaver-config:
    external: false
    name: mkvcleaver-config

  handbrake-config:
    external: false
    name: handbrake-config

  raw-ingest:
    external: false
    name: raw-ingest

  movies-ingest:
    external: false
    name: movies-ingest

  shows-ingest:
    external: false
    name: shows-ingest

  movies:
    driver: local
    driver_opts:
      type: none
      device: /mnt/movies
      o: bind

  shows:
    driver: local
    driver_opts:
      type: none
      device: /mnt/shows
      o: bind