services:
    lubelogger:
        image: ghcr.io/hargata/lubelogger:latest
        # volumes used to keep data persistent
        volumes:
            - lubelogger-data:/App/data
            - lubelogger-keys:/root/.aspnet/DataProtection-Keys
        # expose port and/or use serving via traefik
        networks:
          - diagon-alley
        deploy:
          replicas: 1
    
          placement:
            constraints:
              - node.hostname == srv-01
    
          labels:
            - "traefik.enable=true"
            - "traefik.docker.network=diagon-alley"
    
            # HTTP router
            - "traefik.http.routers.lubelogger.rule=Host(`cars.hogwartsnetwork.co.uk`)"
            - "traefik.http.routers.lubelogger.entrypoints=websecure"
            - "traefik.http.routers.lubelogger.tls=true"
    
            # Technitium web interface
            - "traefik.http.services.lubelogger.loadbalancer.server.port=8080"
    
volumes:
    lubelogger-data:
    lubelogger-keys:

networks:
  diagon-alley:
    external: true