services:
  broker:
    image: docker.io/valkey/valkey:9-alpine
    restart: unless-stopped
    volumes:
      - redisdata:/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == srv-01
      restart_policy:
        condition: on-failure
        
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - broker
      - gotenberg
      - tika
    ports:
      - 8800:8000
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      # - ./export:/usr/src/paperless/export
      - /mnt/consume:/usr/src/paperless/consume
    env_file: .env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBENGINE: sqlite
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == srv-01
      restart_policy:
        condition: on-failure
        
  gotenberg:
    image: docker.io/gotenberg/gotenberg:8.34
    restart: unless-stopped
    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == srv-01
      restart_policy:
        condition: on-failure
        
  tika:
    image: docker.io/apache/tika:latest
    restart: unless-stopped
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == srv-01
      restart_policy:
        condition: on-failure
    
volumes:
  data:
  media:
  redisdata:
