services:
  rackpad:
    image: ghcr.io/kobii-git/rackpad:latest
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 3000
      DATABASE_PATH: /data/rackpad.db

      # Reverse proxy configuration
      TRUST_PROXY: "1"
      TRUSTED_HOSTS: rackpad.hogwartsnetwork.co.uk
      TRUSTED_ORIGINS: https://rackpad.hogwartsnetwork.co.uk

      # Monitoring
      MONITOR_INTERVAL_MS: 300000

    volumes:
      - rackpad_data:/data

    networks:
      - diagon-alley

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

      labels:
        #Enable Traefik
        - "traefik.enable=true"
        
        # Network Traefik should use
        - "traefik.swarm.network=diagon-alley"
        
        # HTTP router
        - "traefik.http.routers.rackpad.rule=Host(`rackpad.hogwartsnetwork.co.uk`)"
        - "traefik.http.routers.rackpad.entrypoints=websecure"
        - "traefik.http.routers.rackpad.tls=true"
        - "traefik.http.routers.rackpad.tls.certresolver=cloudflare"

        # Rackpad listens on 3000 internally
        - "traefik.http.services.rackpad.loadbalancer.server.port=3000"

volumes:
  rackpad_data:
    external: false
    name: rackpad_data

networks:
  diagon-alley:
    external: true
