services:
  radarr:
    image: ghcr.io/hotio/radarr:release-6.3.0.10514
    environment:
      - PUID=0
      - PGID=0
      - UMASK=002
      - TZ=Europe/London
      - WEBUI_PORTS=7878/tcp 
    volumes:
      - radarr-config:/config
      - movies:/movies
    networks:
      - media
      - diagon-alley
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.media == yes
      restart_policy:
        condition: on-failure
      labels:
        # Enable DIUN monitoring    
        - "diun.enable=true"
        # Enable Traefik
        - "traefik.enable=true"
        # Tell Traefik which network to use
        - "traefik.swarm.network=diagon-alley"
        # HTTP router
        - "traefik.http.routers.radarr.rule=Host(`radarr.hogwartsnetwork.co.uk`)"
        - "traefik.http.routers.radarr.entrypoints=websecure"
        # HTTPS
        - "traefik.http.routers.radarr.tls=true"
        - "traefik.http.routers.radarr.tls.certresolver=cloudflare"
        # Paperless internal port
        - "traefik.http.services.radarr.loadbalancer.server.port=7878"
    
volumes:
  radarr-config:
    external: false
    name: radarr-config

  movies:
    driver: local
    driver_opts:
      type: none
      device: /mnt/movies
      o: bind

networks:
  media:
    external: true

  diagon-alley:
    external: true